from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
import sys
import zipfile
from dataclasses import asdict, replace
from datetime import UTC, datetime
from pathlib import Path

import pytest

import scripts.build_sglang_kt_runtime as builder
import scripts.validate_sglang_kt_runtime as validator

GPU_UUID = "GPU-11111111-2222-3333-4444-555555555555"
TIMESTAMP = datetime(2026, 7, 19, 12, 0, tzinfo=UTC)


def test_validator_import_does_not_require_model_download_stack() -> None:
    repository = Path(__file__).resolve().parents[2]
    program = f"""
import importlib.abc
import sys

sys.path.insert(0, {str(repository)!r})

class BlockAiofiles(importlib.abc.MetaPathFinder):
    def find_spec(self, fullname, path, target=None):
        if fullname == "aiofiles" or fullname.startswith("aiofiles."):
            raise ModuleNotFoundError("aiofiles is intentionally unavailable")
        return None

sys.meta_path.insert(0, BlockAiofiles())
import scripts.validate_sglang_kt_runtime
"""

    result = subprocess.run(
        (sys.executable, "-I", "-c", program),
        check=False,
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stderr


def make_config() -> validator.ValidationConfig:
    return validator.ValidationConfig(
        gpu_uuid=GPU_UUID,
        build_receipt_path="/runtime/build-receipt.json",
        worker_pool=validator.WorkerPoolAssignment(
            numa_nodes=(0,),
            threads_per_subpool=(16,),
        ),
    )


def embedded_contents() -> bytes:
    return (
        '"""Generated by Exo\'s pinned SGLang-KTransformers builder."""\n'
        "\n"
        "SCHEMA_VERSION = 1\n"
        f'KTRANSFORMERS_REVISION = "{validator.GLM_4_7_FLASH_KTRANSFORMERS_REVISION}"\n'
        f'SGLANG_REVISION = "{validator.GLM_4_7_FLASH_SGLANG_REVISION}"\n'
    ).encode("ascii")


def make_embedded_provenance(
    distribution: str, location: str
) -> validator.EmbeddedProvenanceEvidence:
    return validator.EmbeddedProvenanceEvidence(
        distribution=distribution,
        location=location,
        sha256=hashlib.sha256(embedded_contents()).hexdigest(),
        schema_version=1,
        ktransformers_revision=validator.GLM_4_7_FLASH_KTRANSFORMERS_REVISION,
        sglang_revision=validator.GLM_4_7_FLASH_SGLANG_REVISION,
    )


def make_provenance() -> validator.BuildProvenanceEvidence:
    wheels = tuple(
        validator.WheelArtifactEvidence(
            distribution=name,
            version=validator.EXPECTED_PACKAGE_VERSION,
            path=f"/runtime/wheels/{name}.whl",
            size_bytes=1000 + index,
            sha256=str(index + 1) * 64,
        )
        for index, name in enumerate(sorted(validator.EXPECTED_WHEEL_DISTRIBUTIONS))
    )
    return validator.BuildProvenanceEvidence(
        receipt_path="/runtime/build-receipt.json",
        receipt_sha256="a" * 64,
        build_id="b" * 64,
        builder_sha256="e" * 64,
        host_profile="dwagon",
        hostname="dwagon",
        ktransformers_revision=validator.GLM_4_7_FLASH_KTRANSFORMERS_REVISION,
        sglang_revision=validator.GLM_4_7_FLASH_SGLANG_REVISION,
        package_version=validator.EXPECTED_PACKAGE_VERSION,
        cuda_architectures="86",
        cpu_features=tuple(sorted(validator.REQUIRED_CPU_FEATURES)),
        build_environment=tuple(sorted(validator.REQUIRED_BUILD_ENVIRONMENT.items())),
        bootstrap_wheels=tuple(
            validator.WheelArtifactEvidence(
                distribution=pin.distribution,
                version=pin.version,
                path=f"/runtime/bootstrap/{pin.filename}",
                size_bytes=100,
                sha256=pin.sha256,
            )
            for pin in validator.BOOTSTRAP_WHEEL_PINS
        ),
        wheels=wheels,
        embedded_provenance=tuple(
            make_embedded_provenance(name, f"{name}/_exo_build_provenance.py")
            for name in ("kt-kernel", "sglang-kt")
        ),
        kt_extension_member="kt_kernel/kt_kernel_ext.cpython-312-x86_64-linux-gnu.so",
        kt_extension_sha256="d" * 64,
        verified=True,
    )


def make_runtime_identity() -> validator.RuntimeIdentityEvidence:
    return validator.RuntimeIdentityEvidence(
        torch_module_version=validator.EXPECTED_TORCH_MODULE_VERSION,
        torch_cuda_version=validator.EXPECTED_TORCH_CUDA_VERSION,
        transformers_distribution_version=(
            validator.EXPECTED_DISTRIBUTION_VERSIONS["transformers-kt"]
        ),
        transformers_module_version=validator.EXPECTED_TRANSFORMERS_MODULE_VERSION,
        sgl_kernel_build_id="5" * 64,
        deep_gemm_build_id="6" * 64,
        kt_kernel_build_id="7" * 64,
        embedded_provenance=tuple(
            make_embedded_provenance(
                name, f"/runtime/site-packages/{name}/_exo_build_provenance.py"
            )
            for name in ("kt-kernel", "sglang-kt")
        ),
    )


def make_packages(
    provenance: validator.BuildProvenanceEvidence,
) -> tuple[validator.PackageEvidence, ...]:
    wheel_hashes = {wheel.distribution: wheel.sha256 for wheel in provenance.wheels}
    return tuple(
        validator.PackageEvidence(
            distribution=name,
            expected_version=expected,
            observed_version=("2.9.1+cu130" if name == "torch" else expected),
            location=f"/runtime/site-packages/{name}",
            installer="pip",
            direct_url_sha256=wheel_hashes.get(name),
        )
        for name, expected in validator.EXPECTED_DISTRIBUTION_VERSIONS.items()
    )


def make_host() -> validator.HostEvidence:
    return validator.HostEvidence(
        process=validator.ProcessEvidence(
            hostname="dwagon",
            executable="/runtime/bin/python",
            python_implementation="CPython",
            python_version=(3, 12, 10),
            pid=100,
            parent_pid=99,
            uid=1000,
            gid=1000,
            cwd="/root/exo",
            argv=("validate_sglang_kt_runtime.py",),
            affinity_cpu_ids=tuple(range(32)),
            allowed_memory_nodes=(0,),
            environment=(("CUDA_VISIBLE_DEVICES", GPU_UUID),),
        ),
        operating_system="Linux-test",
        machine="x86_64",
        cpu_features=tuple(sorted(validator.REQUIRED_CPU_FEATURES)),
        numa_nodes=(validator.NumaNodeEvidence(node=0, cpu_ids=tuple(range(32))),),
        collection_method="direct_execution_only",
        profiler="none",
    )


def make_numerical(shape: tuple[int, ...], seed: int) -> validator.NumericalEvidence:
    return validator.NumericalEvidence(
        shape=shape,
        seed=seed,
        execution_dtype="torch.bfloat16",
        reference_dtype="torch.float32",
        output_finite=True,
        reference_finite=True,
        mean_absolute_error=0.0001,
        maximum_absolute_error=0.001,
        reference_mean_absolute=0.1,
        relative_l1_error=0.001,
        relative_l1_tolerance=0.02,
    )


def make_cuda() -> validator.CudaExecutionEvidence:
    return validator.CudaExecutionEvidence(
        visible_devices=GPU_UUID,
        logical_device_count=1,
        logical_device_index=0,
        gpu_uuid=GPU_UUID,
        pci_bus_id="00000000:65:00.0",
        gpu_name="NVIDIA GeForce RTX 3090",
        compute_capability=(8, 6),
        total_memory_bytes=24 * 1024**3,
        driver_version="590.48.01",
        torch_cuda_version=validator.EXPECTED_TORCH_CUDA_VERSION,
        torch_device_uuid=GPU_UUID,
        numerical=make_numerical((128, 96), validator.RANDOM_SEED),
    )


def make_amx(
    config: validator.ValidationConfig,
    qlen: int,
    route: validator.ExecutionRoute,
) -> validator.AmxExecutionEvidence:
    stream = route == "cuda_stream"
    return validator.AmxExecutionEvidence(
        route=route,
        qlen=qlen,
        kernel_class="AMXBF16_MOE",
        cpu_variant="amx",
        extension_path="/runtime/site-packages/kt_kernel/kt_kernel_ext.so",
        extension_sha256="d" * 64,
        worker_pool=config.worker_pool,
        load_submit_count=1,
        load_sync_count=1,
        direct_forward_submit_count=0 if stream else 1,
        direct_forward_sync_count=0 if stream else 1,
        cuda_stream_api_available=True if stream else None,
        cuda_stream_submit_count=1 if stream else 0,
        cuda_stream_sync_count=1 if stream else 0,
        cuda_stream_id=22 if stream else None,
        default_cuda_stream_id=11 if stream else None,
        cuda_input_producer_count=1 if stream else 0,
        cuda_input_to_cpu_copy_count=1 if stream else 0,
        cuda_output_from_cpu_copy_count=1 if stream else 0,
        cuda_output_consumer_count=1 if stream else 0,
        cuda_input_produced_checksum=(
            qlen * validator.HIDDEN_SIZE * validator.CUDA_STREAM_INPUT_VALUE
            if stream
            else None
        ),
        cpu_input_observed_checksum=(
            qlen * validator.HIDDEN_SIZE * validator.CUDA_STREAM_INPUT_VALUE
            if stream
            else None
        ),
        cuda_output_consumed_l1=10.0 if stream else None,
        cuda_output_reference_l1=10.0 if stream else None,
        numerical=make_numerical(
            (qlen, validator.HIDDEN_SIZE), validator.RANDOM_SEED + qlen
        ),
    )


class FakeBackend:
    def __init__(self, config: validator.ValidationConfig) -> None:
        self.provenance = make_provenance()
        self.packages = make_packages(self.provenance)
        self.runtime_identity = make_runtime_identity()
        self.host = make_host()
        self.cuda = make_cuda()
        self.amx = {
            (qlen, route): make_amx(config, qlen, route)
            for qlen, route in (
                (1, "direct"),
                (16, "direct"),
                (1, "cuda_stream"),
            )
        }
        self.calls: list[str] = []
        self.error_step: str | None = None

    def _raise_if_requested(self, step: str) -> None:
        if self.error_step == step:
            raise RuntimeError(f"injected {step} failure")

    def observe_provenance(
        self, config: validator.ValidationConfig
    ) -> validator.BuildProvenanceEvidence:
        assert config.gpu_uuid == GPU_UUID
        self.calls.append("provenance")
        self._raise_if_requested("provenance")
        return self.provenance

    def observe_packages(self) -> tuple[validator.PackageEvidence, ...]:
        self.calls.append("packages")
        self._raise_if_requested("packages")
        return self.packages

    def observe_runtime_identity(self) -> validator.RuntimeIdentityEvidence:
        self.calls.append("runtime_identity")
        self._raise_if_requested("runtime_identity")
        return self.runtime_identity

    def observe_host(self) -> validator.HostEvidence:
        self.calls.append("host")
        self._raise_if_requested("host")
        return self.host

    def run_cuda(
        self, config: validator.ValidationConfig
    ) -> validator.CudaExecutionEvidence:
        assert config.gpu_uuid == GPU_UUID
        self.calls.append("cuda")
        self._raise_if_requested("cuda")
        return self.cuda

    def run_amx(
        self,
        config: validator.ValidationConfig,
        qlen: int,
        route: validator.ExecutionRoute,
    ) -> validator.AmxExecutionEvidence:
        assert config.worker_pool.numa_nodes == (0,)
        step = f"amx:{qlen}:{route}"
        self.calls.append(step)
        self._raise_if_requested(step)
        return self.amx[(qlen, route)]


def execute(
    config: validator.ValidationConfig,
    backend: FakeBackend,
) -> validator.RuntimeValidationReceipt:
    return validator.execute_validation(config, backend, clock=lambda: TIMESTAMP)


def test_passes_only_complete_direct_execution_evidence() -> None:
    config = make_config()
    backend = FakeBackend(config)

    receipt = execute(config, backend)

    assert receipt.status == "passed"
    assert receipt.failures == ()
    assert receipt.capabilities == ("kt_bf16_amx_executed_v1",)
    assert receipt.profiler == "none"
    assert [item.qlen for item in receipt.amx] == [1, 16]
    assert backend.calls == [
        "provenance",
        "packages",
        "runtime_identity",
        "host",
        "cuda",
        "amx:1:direct",
        "amx:16:direct",
        "amx:1:cuda_stream",
    ]
    document = json.loads(validator.receipt_json(receipt))
    assert document["status"] == "passed"
    assert document["config"]["worker_pool"]["threads_per_subpool"] == [16]


def test_static_package_failure_gates_all_native_execution() -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.packages = tuple(
        replace(item, observed_version="0.0")
        if item.distribution == "kt-kernel"
        else item
        for item in backend.packages
    )

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert "packages: kt-kernel version is not 0.6.3.post1" in receipt.failures
    assert backend.calls == ["provenance", "packages", "runtime_identity", "host"]
    assert receipt.cuda is None
    assert receipt.amx == ()


def test_build_wheel_must_match_installed_direct_url() -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.packages = tuple(
        replace(item, direct_url_sha256=None)
        if item.distribution == "sglang-kt"
        else item
        for item in backend.packages
    )

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert "packages: sglang-kt install is not bound to build wheel" in receipt.failures
    assert backend.calls == ["provenance", "packages", "runtime_identity", "host"]


def test_static_backend_exception_becomes_structured_failure() -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.error_step = "provenance"

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert receipt.capabilities == ()
    assert receipt.failures == (
        "provenance: RuntimeError: injected provenance failure",
    )
    assert backend.calls == ["provenance", "packages", "runtime_identity", "host"]


def test_wrong_cuda_capability_fails_after_collecting_all_workloads() -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.cuda = replace(backend.cuda, compute_capability=(9, 0))

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert "cuda: selected GPU is not compute capability 8.6" in receipt.failures
    assert receipt.capabilities == ()
    assert backend.calls[-1] == "amx:1:cuda_stream"


def test_torch_logical_device_uuid_must_match_selected_uuid() -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.cuda = replace(
        backend.cuda,
        torch_device_uuid="GPU-aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    )

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert "cuda: Torch logical device 0 UUID is not exact" in receipt.failures


def test_amx_accuracy_and_worker_assignment_fail_closed() -> None:
    config = make_config()
    backend = FakeBackend(config)
    evidence = backend.amx[(16, "direct")]
    backend.amx[(16, "direct")] = replace(
        evidence,
        worker_pool=validator.WorkerPoolAssignment(
            numa_nodes=(1,), threads_per_subpool=(8,)
        ),
        numerical=replace(
            evidence.numerical,
            relative_l1_error=0.021,
        )
        if evidence.numerical is not None
        else None,
    )

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert "amx qlen=16: WorkerPoolConfig assignment changed" in receipt.failures
    assert "amx qlen=16: relative L1 error exceeds tolerance" in receipt.failures


def test_backend_cannot_widen_numerical_tolerance() -> None:
    config = make_config()
    backend = FakeBackend(config)
    evidence = backend.amx[(1, "direct")]
    assert evidence.numerical is not None
    backend.amx[(1, "direct")] = replace(
        evidence,
        numerical=replace(
            evidence.numerical,
            relative_l1_error=0.5,
            relative_l1_tolerance=1.0,
        ),
    )

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert "amx qlen=1: numerical tolerance is not exact" in receipt.failures
    assert "amx qlen=1: relative L1 error exceeds tolerance" in receipt.failures


def test_cuda_stream_bridge_enqueues_both_dependency_directions() -> None:
    calls: list[str] = []

    def record(name: str, result: object = None) -> object:
        calls.append(name)
        return result

    consumed, counts = validator._enqueue_cuda_stream_bridge(  # pyright: ignore[reportPrivateUsage]
        produce_cuda_input=lambda: record("cuda input producer"),
        copy_cuda_input_to_cpu=lambda: record("cuda to cpu copy"),
        submit_cpu_work=lambda: record("cpu submit"),
        sync_cpu_work=lambda: record("cpu sync"),
        copy_cpu_output_to_cuda=lambda: record("cpu to cuda copy"),
        consume_cuda_output=lambda: record("cuda output consumer", "consumed"),
    )

    assert consumed == "consumed"
    assert calls == [
        "cuda input producer",
        "cuda to cpu copy",
        "cpu submit",
        "cpu sync",
        "cpu to cuda copy",
        "cuda output consumer",
    ]
    assert counts.input_producer == 1
    assert counts.input_to_cpu_copy == 1
    assert counts.output_from_cpu_copy == 1
    assert counts.output_consumer == 1


@pytest.mark.parametrize(
    ("changes", "failure"),
    [
        (
            {"cuda_stream_api_available": False},
            "cuda stream: KT CUDA-stream API is unavailable",
        ),
        (
            {"cuda_stream_id": 11},
            "cuda stream: stream was not non-default",
        ),
        (
            {"cuda_input_producer_count": 0},
            "cuda stream: two-way ordering counts are not exact",
        ),
        (
            {"cuda_input_to_cpu_copy_count": 0},
            "cuda stream: two-way ordering counts are not exact",
        ),
        (
            {"cuda_output_from_cpu_copy_count": 0},
            "cuda stream: two-way ordering counts are not exact",
        ),
        (
            {"cuda_output_consumer_count": 0},
            "cuda stream: two-way ordering counts are not exact",
        ),
        (
            {"cpu_input_observed_checksum": 0.0},
            "cuda stream: CUDA-produced input did not reach AMX input",
        ),
        (
            {"cuda_output_consumed_l1": 20.0},
            "cuda stream: AMX output was not consumed by CUDA",
        ),
    ],
)
def test_cuda_stream_path_is_admitted_only_with_real_ordered_callbacks(
    changes: dict[str, object], failure: str
) -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.amx[(1, "cuda_stream")] = replace(
        backend.amx[(1, "cuda_stream")], **changes
    )

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert failure in receipt.failures


def test_cuda_stream_backend_exception_is_structured_and_fails_closed() -> None:
    config = make_config()
    backend = FakeBackend(config)
    backend.error_step = "amx:1:cuda_stream"

    receipt = execute(config, backend)

    assert receipt.status == "failed"
    assert receipt.capabilities == ()
    assert receipt.cuda_stream is None
    assert (
        "cuda stream: RuntimeError: injected amx:1:cuda_stream failure"
        in receipt.failures
    )
    assert "cuda stream: execution evidence is missing" in receipt.failures


def test_worker_pool_assignment_rejects_implicit_or_invalid_layouts() -> None:
    with pytest.raises(ValueError, match="at least one NUMA"):
        validator.WorkerPoolAssignment((), ())
    with pytest.raises(ValueError, match="equal lengths"):
        validator.WorkerPoolAssignment((0, 1), (16,))
    with pytest.raises(ValueError, match="unique"):
        validator.WorkerPoolAssignment((0, 0), (8, 8))
    with pytest.raises(ValueError, match="positive"):
        validator.WorkerPoolAssignment((0,), (0,))


def write_test_build_receipt(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Path, tuple[Path, ...]]:
    staging = tmp_path / "bootstrap-staging"
    staging.mkdir()
    bootstrap_paths: list[Path] = []
    test_bootstrap_pins: list[builder.BootstrapWheelPin] = []
    for pin in builder.BOOTSTRAP_WHEEL_PINS:
        path = staging / pin.filename
        with zipfile.ZipFile(path, "w") as archive:
            archive.writestr(f"{pin.distribution}/__init__.py", pin.version)
        bootstrap_paths.append(path)
        test_bootstrap_pins.append(
            replace(pin, sha256=hashlib.sha256(path.read_bytes()).hexdigest())
        )
    pinned_bootstrap = tuple(test_bootstrap_pins)
    monkeypatch.setattr(builder, "BOOTSTRAP_WHEEL_PINS", pinned_bootstrap)
    monkeypatch.setattr(validator, "BOOTSTRAP_WHEEL_PINS", pinned_bootstrap)

    source = builder.RuntimeSourceObservation(
        ktransformers_source=str(tmp_path / "source/ktransformers"),
        ktransformers_revision=validator.GLM_4_7_FLASH_KTRANSFORMERS_REVISION,
        sglang_revision=validator.GLM_4_7_FLASH_SGLANG_REVISION,
        package_version=validator.EXPECTED_PACKAGE_VERSION,
        source_date_epoch=1_768_000_000,
        submodules=(
            builder.SubmoduleObservation("third_party/llama.cpp", "1" * 40),
            builder.SubmoduleObservation("third_party/pybind11", "2" * 40),
            builder.SubmoduleObservation(
                "third_party/sglang", validator.GLM_4_7_FLASH_SGLANG_REVISION
            ),
        ),
    )
    tool_names = (
        "cc",
        "cmake",
        "cudart_static",
        "cxx",
        "ninja",
        "nvcc",
        "python",
    )
    tools = tuple(
        builder.ToolObservation(
            name=name,
            path=str(tmp_path / "tools" / name),
            sha256=hashlib.sha256(name.encode()).hexdigest(),
            version=f"{name} test version",
        )
        for name in tool_names
    )
    toolchain = builder.RuntimeToolchainObservation(
        host_profile="dwagon",
        hostname="dwagon",
        operating_system="Linux",
        machine="x86_64",
        python_version="3.12.10",
        python_implementation="CPython",
        python_soabi="cpython-312-x86_64-linux-gnu",
        cuda_root="/opt/cuda",
        cuda_version="13.1.80",
        cuda_version_manifest_sha256="3" * 64,
        cuda_architectures="86",
        cpu_features=(
            "amx_bf16",
            "amx_int8",
            "amx_tile",
            "avx512_bf16",
            "avx512_vnni",
            "avx512f",
            "avx512vbmi",
        ),
        tools=tools,
    )
    builder_sha256 = hashlib.sha256(Path(builder.__file__).read_bytes()).hexdigest()
    profile = builder.HOST_BUILD_PROFILES["dwagon"]
    build_id = builder.calculate_runtime_build_id(
        source, toolchain, profile, builder_sha256
    )
    build_root = tmp_path / "runtime" / "dwagon" / build_id
    layout = builder.RuntimeBuildLayout(
        build_root=str(build_root),
        state=str(build_root / "state"),
        cache=str(build_root / "cache"),
        logs=str(build_root / "state/logs"),
        wheels=str(build_root / "wheels"),
        receipt=str(build_root / "build-receipt.json"),
    )
    wheel_directory = build_root / "wheels"
    wheel_directory.mkdir(parents=True)
    bootstrap_directory = build_root / "state/bootstrap-wheels"
    bootstrap_directory.mkdir(parents=True)
    bootstrap_artifacts: list[dict[str, object]] = []
    for pin, staging_path in zip(pinned_bootstrap, bootstrap_paths, strict=True):
        path = bootstrap_directory / pin.filename
        shutil.copyfile(staging_path, path)
        bootstrap_artifacts.append(
            {
                "distribution": pin.distribution,
                "version": pin.version,
                "filename": pin.filename,
                "path": path.relative_to(build_root).as_posix(),
                "size_bytes": path.stat().st_size,
                "sha256": pin.sha256,
                "root_is_purelib": True,
                "tags": ["py3-none-any"],
            }
        )
    artifacts: list[dict[str, object]] = []
    wheel_paths: list[Path] = []
    for distribution in sorted(validator.EXPECTED_WHEEL_DISTRIBUTIONS):
        path = wheel_directory / f"{distribution}-0.6.3.post1-py3-none-any.whl"
        with zipfile.ZipFile(path, "w") as archive:
            archive.writestr(f"{distribution.replace('-', '_')}/__init__.py", "")
            if distribution == "kt-kernel":
                archive.writestr(
                    "kt_kernel/_exo_build_provenance.py", embedded_contents()
                )
                archive.writestr(
                    "kt_kernel/kt_kernel_ext.cpython-312-x86_64-linux-gnu.so",
                    b"native-amx-sm86-extension",
                )
            elif distribution == "sglang-kt":
                archive.writestr("sglang/_exo_build_provenance.py", embedded_contents())
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        artifacts.append(
            {
                "distribution": distribution,
                "version": validator.EXPECTED_PACKAGE_VERSION,
                "filename": path.name,
                "path": path.relative_to(build_root).as_posix(),
                "size_bytes": path.stat().st_size,
                "sha256": digest,
                "root_is_purelib": distribution != "kt-kernel",
                "tags": ["py3-none-any"],
            }
        )
        wheel_paths.append(path)
    receipt_path = build_root / "build-receipt.json"
    document = {
        "schema_version": 2,
        "status": "wheel_build_complete",
        "build_id": build_id,
        "builder_sha256": builder_sha256,
        "source": asdict(source),
        "toolchain": asdict(toolchain),
        "layout": asdict(layout),
        "build_environment": builder.runtime_build_environment(
            source, toolchain, profile, layout
        ),
        "commands": builder.runtime_build_commands(
            Path(toolchain.tool("python").path), layout
        ),
        "bootstrap_wheels": bootstrap_artifacts,
        "runtime_wheels": artifacts,
        "completed_at_utc": "2026-07-19T12:00:00+00:00",
    }
    receipt_path.write_text(json.dumps(document))
    return receipt_path, tuple(wheel_paths)


def test_build_provenance_rehashes_receipt_wheels_and_native_extension(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    receipt_path, _ = write_test_build_receipt(tmp_path, monkeypatch)

    evidence = validator.observe_build_provenance(receipt_path)

    assert evidence.verified is True
    assert evidence.ktransformers_revision == (
        validator.GLM_4_7_FLASH_KTRANSFORMERS_REVISION
    )
    assert evidence.sglang_revision == validator.GLM_4_7_FLASH_SGLANG_REVISION
    assert evidence.kt_extension_member.endswith(".so")
    assert (
        evidence.kt_extension_sha256
        == hashlib.sha256(b"native-amx-sm86-extension").hexdigest()
    )
    assert len(evidence.wheels) == 3
    assert len(evidence.bootstrap_wheels) == 3


def test_build_provenance_rejects_wheel_changed_after_receipt(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    receipt_path, wheel_paths = write_test_build_receipt(tmp_path, monkeypatch)
    with wheel_paths[0].open("ab") as wheel:
        wheel.write(b"tampered")

    with pytest.raises(
        validator.RuntimeValidationError, match="does not match receipt"
    ):
        validator.observe_build_provenance(receipt_path)


def test_build_provenance_rejects_bootstrap_wheel_changed_after_receipt(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    receipt_path, _ = write_test_build_receipt(tmp_path, monkeypatch)
    document = json.loads(receipt_path.read_text())
    bootstrap_path = receipt_path.parent / document["bootstrap_wheels"][0]["path"]
    contents = bytearray(bootstrap_path.read_bytes())
    contents[-1] ^= 1
    bootstrap_path.write_bytes(contents)

    with pytest.raises(validator.RuntimeValidationError, match="pinned SHA-256"):
        validator.observe_build_provenance(receipt_path)


def test_build_provenance_recomputes_build_id_from_full_contract(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    receipt_path, _ = write_test_build_receipt(tmp_path, monkeypatch)
    document = json.loads(receipt_path.read_text())
    document["toolchain"]["tools"][0]["version"] = "altered compiler"
    receipt_path.write_text(json.dumps(document))

    with pytest.raises(
        validator.RuntimeValidationError, match="build_id does not match its contract"
    ):
        validator.observe_build_provenance(receipt_path)


def test_build_provenance_rejects_noncanonical_commands(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    receipt_path, _ = write_test_build_receipt(tmp_path, monkeypatch)
    document = json.loads(receipt_path.read_text())
    document["commands"][2].append("--altered")
    receipt_path.write_text(json.dumps(document))

    with pytest.raises(
        validator.RuntimeValidationError, match="commands are not canonical"
    ):
        validator.observe_build_provenance(receipt_path)


def test_build_provenance_rejects_hand_authored_incomplete_receipt(
    tmp_path: Path,
) -> None:
    receipt_path = tmp_path / "build-receipt.json"
    receipt_path.write_text(
        json.dumps(
            {
                "schema_version": 2,
                "status": "wheel_build_complete",
                "build_id": "b" * 64,
                "builder_sha256": "c" * 64,
            }
        )
    )

    with pytest.raises(validator.RuntimeValidationError, match="keys are not exact"):
        validator.observe_build_provenance(receipt_path)


def test_write_receipt_is_atomic_json(tmp_path: Path) -> None:
    config = make_config()
    receipt = execute(config, FakeBackend(config))
    destination = tmp_path / "nested" / "receipt.json"

    validator.write_receipt(destination, receipt)

    document = json.loads(destination.read_text())
    assert document["status"] == "passed"
    assert not tuple(destination.parent.glob(f".{destination.name}.*.tmp"))
    assert destination.stat().st_uid == os.getuid()
