#!/usr/bin/env python3
"""Stage the pinned DSV4 AVX-tail KT extension in an isolated package overlay.

The installed ``kt_kernel`` package is treated as immutable input.  This
helper copies its importable payload to a content-addressed cache directory,
replaces the candidate's exact extension filename and, when explicitly
requested, the package's ``experts_base.py`` module, verifies the complete
staged package, and atomically publishes the overlay.  Its sole stdout line is
the overlay root suitable for prepending to ``PYTHONPATH``.
"""

from __future__ import annotations

import argparse
import fcntl
import hashlib
import importlib.util
import json
import os
import re
import shutil
import stat
import sys
import tempfile
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Final, Literal, Protocol, cast

PACKAGE_NAME: Final = "kt_kernel"
RECEIPT_NAME: Final = "overlay.json"
SCHEMA_VERSION: Final = 1
DEFAULT_CANDIDATE: Final = Path(
    "/var/lib/exo/experiments/dsv4-avx-tail23-nblock128/lib/kt_kernel/"
    "kt_kernel_ext.cpython-312-x86_64-linux-gnu.so"
)
REQUIRED_CANDIDATE_SHA256: Final = (
    "32cbe088f6263bfb02c08eb1d7279de1d800147f25bfab5fa293888b2cddc0df"
)
DEFAULT_CACHE_ROOT: Final = Path("/var/lib/exo/cache/dsv4-kt-kernel-overlays")
SHA256_PATTERN: Final = re.compile(r"[0-9a-f]{64}", re.ASCII)
EXTENSION_PATTERN: Final = re.compile(
    r"kt_kernel_ext\.cpython-[0-9]+-[A-Za-z0-9_.-]+\.so", re.ASCII
)
BYTECODE_SUFFIXES: Final = frozenset((".pyc", ".pyo"))
PYTHON_REPLACEMENT_RELATIVE_PATH: Final = "experts_base.py"


class OverlayStageError(RuntimeError):
    """Raised when an input or staged overlay fails closed verification."""


EntryKind = Literal["directory", "file"]


@dataclass(frozen=True)
class PackageEntry:
    relative_path: str
    kind: EntryKind
    mode: int
    size_bytes: int | None = None
    sha256: str | None = None


@dataclass(frozen=True)
class PackageSnapshot:
    entries: tuple[PackageEntry, ...]
    manifest_sha256: str


class _ParsedArguments(Protocol):
    candidate: Path
    expected_sha256: str
    cache_root: Path
    package_dir: Path | None
    python_source: Path | None
    expected_python_sha256: str | None


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as source:
            while chunk := source.read(1024 * 1024):
                digest.update(chunk)
    except OSError as error:
        raise OverlayStageError(f"cannot hash {path}: {error}") from error
    return digest.hexdigest()


def _canonical_json(value: object) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("ascii")


def _manifest_sha256(entries: Sequence[PackageEntry]) -> str:
    return hashlib.sha256(
        _canonical_json([asdict(entry) for entry in entries])
    ).hexdigest()


def _is_ignored_bytecode(path: Path, *, is_directory: bool) -> bool:
    if is_directory:
        return path.name == "__pycache__"
    return path.suffix in BYTECODE_SUFFIXES


def snapshot_package(package_directory: Path) -> PackageSnapshot:
    """Hash an importable package payload, excluding generated bytecode."""

    if not package_directory.is_dir() or package_directory.is_symlink():
        raise OverlayStageError(
            f"package directory is not a real directory: {package_directory}"
        )

    entries: list[PackageEntry] = []

    def visit(directory: Path, relative_directory: Path) -> None:
        try:
            children = sorted(os.scandir(directory), key=lambda entry: entry.name)
        except OSError as error:
            raise OverlayStageError(
                f"cannot scan package {directory}: {error}"
            ) from error

        for child in children:
            child_path = Path(child.path)
            relative_path = relative_directory / child.name
            if child.is_symlink():
                raise OverlayStageError(
                    f"package payload contains unsupported symlink: {child_path}"
                )
            try:
                metadata = child.stat(follow_symlinks=False)
            except OSError as error:
                raise OverlayStageError(f"cannot stat {child_path}: {error}") from error

            if child.is_dir(follow_symlinks=False):
                if _is_ignored_bytecode(child_path, is_directory=True):
                    continue
                entries.append(
                    PackageEntry(
                        relative_path=relative_path.as_posix(),
                        kind="directory",
                        mode=stat.S_IMODE(metadata.st_mode),
                    )
                )
                visit(child_path, relative_path)
                continue

            if child.is_file(follow_symlinks=False):
                if _is_ignored_bytecode(child_path, is_directory=False):
                    continue
                entries.append(
                    PackageEntry(
                        relative_path=relative_path.as_posix(),
                        kind="file",
                        mode=stat.S_IMODE(metadata.st_mode),
                        size_bytes=metadata.st_size,
                        sha256=sha256_file(child_path),
                    )
                )
                continue

            raise OverlayStageError(
                f"package payload contains unsupported filesystem entry: {child_path}"
            )

    visit(package_directory, Path())
    snapshot_entries = tuple(entries)
    return PackageSnapshot(
        entries=snapshot_entries,
        manifest_sha256=_manifest_sha256(snapshot_entries),
    )


def discover_installed_package() -> Path:
    try:
        specification = importlib.util.find_spec(PACKAGE_NAME)
    except (ImportError, AttributeError, ValueError) as error:
        raise OverlayStageError(
            f"cannot locate installed {PACKAGE_NAME}: {error}"
        ) from error
    if specification is None or specification.submodule_search_locations is None:
        raise OverlayStageError(f"cannot locate installed package {PACKAGE_NAME}")
    locations = tuple(specification.submodule_search_locations)
    if len(locations) != 1:
        raise OverlayStageError(
            f"installed {PACKAGE_NAME} must have exactly one package directory; "
            f"observed {locations!r}"
        )
    return _resolve_existing_directory(Path(locations[0]), "installed package")


def _resolve_existing_file(path: Path, description: str) -> Path:
    if not path.is_absolute():
        raise OverlayStageError(f"{description} path must be absolute: {path}")
    if path.is_symlink():
        raise OverlayStageError(f"{description} must not be a symlink: {path}")
    try:
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise OverlayStageError(
            f"cannot resolve {description} {path}: {error}"
        ) from error
    if not resolved.is_file():
        raise OverlayStageError(f"{description} is not a regular file: {resolved}")
    return resolved


def _resolve_existing_directory(path: Path, description: str) -> Path:
    if not path.is_absolute():
        raise OverlayStageError(f"{description} path must be absolute: {path}")
    if path.is_symlink():
        raise OverlayStageError(f"{description} must not be a symlink: {path}")
    try:
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise OverlayStageError(
            f"cannot resolve {description} {path}: {error}"
        ) from error
    if not resolved.is_dir():
        raise OverlayStageError(f"{description} is not a directory: {resolved}")
    return resolved


def _prepare_cache_root(path: Path, package_directory: Path) -> Path:
    if not path.is_absolute():
        raise OverlayStageError(f"cache root path must be absolute: {path}")
    if path.is_symlink():
        raise OverlayStageError(f"cache root must not be a symlink: {path}")
    try:
        prospective = path.resolve(strict=False)
    except (OSError, RuntimeError) as error:
        raise OverlayStageError(f"cannot resolve cache root {path}: {error}") from error
    if prospective == package_directory or prospective.is_relative_to(
        package_directory
    ):
        raise OverlayStageError(
            "cache root must not be the installed package or a child of it: "
            f"{prospective}"
        )
    try:
        path.mkdir(parents=True, exist_ok=True, mode=0o755)
        resolved = path.resolve(strict=True)
    except OSError as error:
        raise OverlayStageError(f"cannot prepare cache root {path}: {error}") from error
    if not resolved.is_dir():
        raise OverlayStageError(f"cache root is not a directory: {resolved}")
    if resolved == package_directory or resolved.is_relative_to(package_directory):
        raise OverlayStageError(
            f"cache root must not be the installed package or a child of it: {resolved}"
        )
    return resolved


def _validate_candidate_name(candidate: Path) -> str:
    name = candidate.name
    if EXTENSION_PATTERN.fullmatch(name) is None:
        raise OverlayStageError(
            "candidate filename is not an exact CPython kt_kernel extension name: "
            f"{name}"
        )
    return name


def _require_sha256(value: str, description: str) -> str:
    if SHA256_PATTERN.fullmatch(value) is None:
        raise OverlayStageError(
            f"{description} must be a lowercase 64-character SHA-256 digest"
        )
    return value


def _find_extension_entry(
    snapshot: PackageSnapshot, extension_name: str
) -> PackageEntry:
    matches = [
        entry
        for entry in snapshot.entries
        if entry.relative_path == extension_name and entry.kind == "file"
    ]
    if len(matches) != 1:
        raise OverlayStageError(
            f"installed package must contain one regular {extension_name}; "
            f"observed {len(matches)}"
        )
    return matches[0]


def _find_python_replacement_entry(snapshot: PackageSnapshot) -> PackageEntry:
    matches = [
        entry
        for entry in snapshot.entries
        if entry.relative_path == PYTHON_REPLACEMENT_RELATIVE_PATH
        and entry.kind == "file"
    ]
    if len(matches) != 1:
        raise OverlayStageError(
            "installed package must contain one regular "
            f"{PYTHON_REPLACEMENT_RELATIVE_PATH}; observed {len(matches)}"
        )
    return matches[0]


def _expected_staged_snapshot(
    source_snapshot: PackageSnapshot,
    source_extension: PackageEntry,
    candidate_sha256: str,
    candidate_size_bytes: int,
    source_python: PackageEntry | None = None,
    replacement_python_sha256: str | None = None,
    replacement_python_size_bytes: int | None = None,
) -> PackageSnapshot:
    extension_replacement = replace(
        source_extension,
        size_bytes=candidate_size_bytes,
        sha256=candidate_sha256,
    )
    python_replacement: PackageEntry | None = None
    if source_python is not None:
        if replacement_python_sha256 is None or replacement_python_size_bytes is None:
            raise OverlayStageError(
                "internal error: Python replacement metadata is incomplete"
            )
        python_replacement = replace(
            source_python,
            size_bytes=replacement_python_size_bytes,
            sha256=replacement_python_sha256,
        )
    elif (
        replacement_python_sha256 is not None
        or replacement_python_size_bytes is not None
    ):
        raise OverlayStageError(
            "internal error: Python replacement metadata has no source entry"
        )

    entries = tuple(
        extension_replacement
        if entry == source_extension
        else python_replacement
        if python_replacement is not None and entry == source_python
        else entry
        for entry in source_snapshot.entries
    )
    return PackageSnapshot(entries=entries, manifest_sha256=_manifest_sha256(entries))


def _copy_ignore(_directory: str, names: list[str]) -> set[str]:
    ignored: set[str] = set()
    for name in names:
        if name == "__pycache__" or Path(name).suffix in BYTECODE_SUFFIXES:
            ignored.add(name)
    return ignored


def _copy_package(source: Path, destination: Path) -> None:
    try:
        shutil.copytree(
            source,
            destination,
            symlinks=True,
            ignore=_copy_ignore,
            copy_function=shutil.copy2,
        )
    except OSError as error:
        raise OverlayStageError(
            f"cannot copy installed package {source} to {destination}: {error}"
        ) from error


def _replace_extension(candidate: Path, destination: Path) -> None:
    """Replace bytes while retaining the installed extension's permissions."""

    try:
        shutil.copyfile(candidate, destination, follow_symlinks=False)
    except OSError as error:
        raise OverlayStageError(
            f"cannot stage candidate extension {candidate} at {destination}: {error}"
        ) from error


def _replace_python_module(source: Path, destination: Path) -> None:
    """Replace bytes while retaining the installed module's permissions."""

    try:
        shutil.copyfile(source, destination, follow_symlinks=False)
    except OSError as error:
        raise OverlayStageError(
            f"cannot stage Python module {source} at {destination}: {error}"
        ) from error


def _identity_document(
    *,
    package_directory: Path,
    source_snapshot: PackageSnapshot,
    extension_name: str,
    candidate: Path,
    candidate_sha256: str,
    python_source: Path | None = None,
    python_source_sha256: str | None = None,
) -> dict[str, object]:
    identity: dict[str, object] = {
        "schema_version": SCHEMA_VERSION,
        "package_name": PACKAGE_NAME,
        "source_package_directory": str(package_directory),
        "source_package_manifest_sha256": source_snapshot.manifest_sha256,
        "extension_relative_path": extension_name,
        "candidate_extension_path": str(candidate),
        "candidate_extension_sha256": candidate_sha256,
    }
    if python_source is not None:
        if python_source_sha256 is None:
            raise OverlayStageError(
                "internal error: Python source digest is missing from identity"
            )
        identity.update(
            {
                "python_replacement_relative_path": (PYTHON_REPLACEMENT_RELATIVE_PATH),
                "python_source_path": str(python_source),
                "python_source_sha256": python_source_sha256,
            }
        )
    elif python_source_sha256 is not None:
        raise OverlayStageError(
            "internal error: Python source digest has no source path"
        )
    return identity


def _receipt_document(
    *,
    identity: dict[str, object],
    identity_sha256: str,
    source_extension_sha256: str,
    staged_snapshot: PackageSnapshot,
    source_python_sha256: str | None = None,
) -> dict[str, object]:
    receipt: dict[str, object] = {
        **identity,
        "status": "complete",
        "cache_identity_sha256": identity_sha256,
        "source_extension_sha256": source_extension_sha256,
        "staged_package_manifest_sha256": staged_snapshot.manifest_sha256,
    }
    if source_python_sha256 is not None:
        receipt["source_python_sha256"] = source_python_sha256
    return receipt


def _write_receipt(path: Path, document: dict[str, object]) -> None:
    encoded = json.dumps(document, indent=2, sort_keys=True) + "\n"
    try:
        with path.open("x", encoding="utf-8") as destination:
            destination.write(encoded)
            destination.flush()
            os.fsync(destination.fileno())
    except OSError as error:
        raise OverlayStageError(
            f"cannot write overlay receipt {path}: {error}"
        ) from error


def _load_receipt(path: Path) -> object:
    try:
        return cast(object, json.loads(path.read_text(encoding="utf-8")))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        raise OverlayStageError(
            f"cannot read overlay receipt {path}: {error}"
        ) from error


def _validate_overlay(
    overlay_root: Path,
    *,
    expected_snapshot: PackageSnapshot,
    expected_receipt: dict[str, object],
) -> None:
    if not overlay_root.is_dir() or overlay_root.is_symlink():
        raise OverlayStageError(
            f"published overlay is not a real directory: {overlay_root}"
        )
    try:
        top_level_names = {entry.name for entry in os.scandir(overlay_root)}
    except OSError as error:
        raise OverlayStageError(
            f"cannot scan overlay {overlay_root}: {error}"
        ) from error
    expected_names = {PACKAGE_NAME, RECEIPT_NAME}
    if top_level_names != expected_names:
        raise OverlayStageError(
            f"overlay {overlay_root} has unexpected top-level entries: "
            f"expected {sorted(expected_names)}, observed {sorted(top_level_names)}"
        )

    package_directory = overlay_root / PACKAGE_NAME
    observed_snapshot = snapshot_package(package_directory)
    if observed_snapshot != expected_snapshot:
        raise OverlayStageError(
            f"staged package verification failed at {package_directory}: "
            f"expected manifest {expected_snapshot.manifest_sha256}, observed "
            f"{observed_snapshot.manifest_sha256}"
        )
    observed_receipt = _load_receipt(overlay_root / RECEIPT_NAME)
    if observed_receipt != expected_receipt:
        raise OverlayStageError(
            f"overlay receipt verification failed at {overlay_root / RECEIPT_NAME}"
        )


@contextmanager
def _cache_lock(cache_root: Path) -> Iterator[None]:
    lock_path = cache_root / ".stage.lock"
    try:
        descriptor = os.open(lock_path, os.O_CREAT | os.O_RDWR, 0o600)
    except OSError as error:
        raise OverlayStageError(
            f"cannot open cache lock {lock_path}: {error}"
        ) from error
    try:
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        yield
    except OSError as error:
        raise OverlayStageError(
            f"cannot lock cache root {cache_root}: {error}"
        ) from error
    finally:
        try:
            fcntl.flock(descriptor, fcntl.LOCK_UN)
        finally:
            os.close(descriptor)


def stage_overlay(
    *,
    candidate: Path = DEFAULT_CANDIDATE,
    expected_candidate_sha256: str = REQUIRED_CANDIDATE_SHA256,
    cache_root: Path = DEFAULT_CACHE_ROOT,
    package_directory: Path | None = None,
    python_source: Path | None = None,
    expected_python_sha256: str | None = None,
) -> Path:
    """Create or verify a content-addressed KT package overlay."""

    required_sha256 = _require_sha256(
        expected_candidate_sha256, "expected candidate digest"
    )
    resolved_candidate = _resolve_existing_file(candidate, "candidate extension")
    extension_name = _validate_candidate_name(resolved_candidate)
    observed_candidate_sha256 = sha256_file(resolved_candidate)
    if observed_candidate_sha256 != required_sha256:
        raise OverlayStageError(
            f"candidate SHA-256 mismatch for {resolved_candidate}: expected "
            f"{required_sha256}, observed {observed_candidate_sha256}"
        )

    if (python_source is None) != (expected_python_sha256 is None):
        raise OverlayStageError(
            "python_source and expected_python_sha256 must be supplied together"
        )
    resolved_python_source: Path | None = None
    observed_python_sha256: str | None = None
    if python_source is not None and expected_python_sha256 is not None:
        required_python_sha256 = _require_sha256(
            expected_python_sha256, "expected Python source digest"
        )
        resolved_python_source = _resolve_existing_file(
            python_source, "Python module source"
        )
        observed_python_sha256 = sha256_file(resolved_python_source)
        if observed_python_sha256 != required_python_sha256:
            raise OverlayStageError(
                f"Python source SHA-256 mismatch for {resolved_python_source}: "
                f"expected {required_python_sha256}, observed "
                f"{observed_python_sha256}"
            )

    resolved_package = (
        discover_installed_package()
        if package_directory is None
        else _resolve_existing_directory(package_directory, "installed package")
    )
    source_snapshot = snapshot_package(resolved_package)
    source_extension = _find_extension_entry(source_snapshot, extension_name)
    if source_extension.sha256 is None:
        raise OverlayStageError(f"installed extension has no digest: {extension_name}")
    source_python = (
        _find_python_replacement_entry(source_snapshot)
        if resolved_python_source is not None
        else None
    )
    if source_python is not None and source_python.sha256 is None:
        raise OverlayStageError(
            f"installed Python module has no digest: {PYTHON_REPLACEMENT_RELATIVE_PATH}"
        )
    candidate_size = resolved_candidate.stat().st_size
    expected_staged_snapshot = _expected_staged_snapshot(
        source_snapshot,
        source_extension,
        observed_candidate_sha256,
        candidate_size,
        source_python=source_python,
        replacement_python_sha256=observed_python_sha256,
        replacement_python_size_bytes=(
            resolved_python_source.stat().st_size
            if resolved_python_source is not None
            else None
        ),
    )

    identity = _identity_document(
        package_directory=resolved_package,
        source_snapshot=source_snapshot,
        extension_name=extension_name,
        candidate=resolved_candidate,
        candidate_sha256=observed_candidate_sha256,
        python_source=resolved_python_source,
        python_source_sha256=observed_python_sha256,
    )
    identity_sha256 = hashlib.sha256(_canonical_json(identity)).hexdigest()
    expected_receipt = _receipt_document(
        identity=identity,
        identity_sha256=identity_sha256,
        source_extension_sha256=source_extension.sha256,
        staged_snapshot=expected_staged_snapshot,
        source_python_sha256=(
            source_python.sha256 if source_python is not None else None
        ),
    )

    resolved_cache_root = _prepare_cache_root(cache_root, resolved_package)
    overlay_root = resolved_cache_root / f"kt-kernel-{identity_sha256}"
    with _cache_lock(resolved_cache_root):
        if overlay_root.exists() or overlay_root.is_symlink():
            _validate_overlay(
                overlay_root,
                expected_snapshot=expected_staged_snapshot,
                expected_receipt=expected_receipt,
            )
            return overlay_root

        staging_root = Path(
            tempfile.mkdtemp(
                prefix=f".{overlay_root.name}.partial-", dir=resolved_cache_root
            )
        )
        published = False
        try:
            staged_package = staging_root / PACKAGE_NAME
            _copy_package(resolved_package, staged_package)
            copied_snapshot = snapshot_package(staged_package)
            if copied_snapshot != source_snapshot:
                raise OverlayStageError(
                    "installed package changed or copied incorrectly while staging: "
                    f"expected manifest {source_snapshot.manifest_sha256}, observed "
                    f"{copied_snapshot.manifest_sha256}"
                )

            _replace_extension(
                resolved_candidate,
                staged_package / extension_name,
            )
            if resolved_python_source is not None:
                _replace_python_module(
                    resolved_python_source,
                    staged_package / PYTHON_REPLACEMENT_RELATIVE_PATH,
                )
            staged_snapshot = snapshot_package(staged_package)
            if staged_snapshot != expected_staged_snapshot:
                raise OverlayStageError(
                    "candidate overlay differs from the installed package outside the "
                    f"pinned artifacts: expected manifest "
                    f"{expected_staged_snapshot.manifest_sha256}, observed "
                    f"{staged_snapshot.manifest_sha256}"
                )
            if sha256_file(staged_package / extension_name) != required_sha256:
                raise OverlayStageError(
                    f"staged extension SHA-256 mismatch at {staged_package / extension_name}"
                )
            if (
                resolved_python_source is not None
                and observed_python_sha256 is not None
                and sha256_file(staged_package / PYTHON_REPLACEMENT_RELATIVE_PATH)
                != observed_python_sha256
            ):
                raise OverlayStageError(
                    "staged Python module SHA-256 mismatch at "
                    f"{staged_package / PYTHON_REPLACEMENT_RELATIVE_PATH}"
                )
            if snapshot_package(resolved_package) != source_snapshot:
                raise OverlayStageError(
                    f"installed package changed during staging: {resolved_package}"
                )

            _write_receipt(staging_root / RECEIPT_NAME, expected_receipt)
            try:
                os.rename(staging_root, overlay_root)
            except OSError as error:
                raise OverlayStageError(
                    f"cannot atomically publish overlay {overlay_root}: {error}"
                ) from error
            published = True
        finally:
            if not published and staging_root.exists():
                shutil.rmtree(staging_root, ignore_errors=True)

        _validate_overlay(
            overlay_root,
            expected_snapshot=expected_staged_snapshot,
            expected_receipt=expected_receipt,
        )
    return overlay_root


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--candidate",
        type=Path,
        default=DEFAULT_CANDIDATE,
        help=f"candidate extension (default: {DEFAULT_CANDIDATE})",
    )
    parser.add_argument(
        "--expected-sha256",
        default=REQUIRED_CANDIDATE_SHA256,
        help="required lowercase SHA-256 for the candidate",
    )
    parser.add_argument(
        "--cache-root",
        type=Path,
        default=DEFAULT_CACHE_ROOT,
        help=f"atomic overlay cache (default: {DEFAULT_CACHE_ROOT})",
    )
    parser.add_argument(
        "--package-dir",
        type=Path,
        help=(
            "explicit installed kt_kernel package directory; by default it is "
            "discovered from this interpreter"
        ),
    )
    parser.add_argument(
        "--python-source",
        type=Path,
        help=(
            "explicit replacement for kt_kernel/experts_base.py; requires "
            "--expected-python-sha256"
        ),
    )
    parser.add_argument(
        "--expected-python-sha256",
        help=(
            "required lowercase SHA-256 for --python-source; the installed "
            "module is retained when both options are omitted"
        ),
    )
    return parser


def main(arguments: Sequence[str] | None = None) -> int:
    parsed = cast(
        _ParsedArguments,
        cast(object, build_parser().parse_args(arguments)),
    )
    try:
        overlay_root = stage_overlay(
            candidate=parsed.candidate,
            expected_candidate_sha256=parsed.expected_sha256,
            cache_root=parsed.cache_root,
            package_directory=parsed.package_dir,
            python_source=parsed.python_source,
            expected_python_sha256=parsed.expected_python_sha256,
        )
    except OverlayStageError as error:
        print(f"stage_dsv4_kt_avx_tail_overlay: {error}", file=sys.stderr)
        return 2
    print(overlay_root)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
